### ISSUE TITLE
Support for UDP Multicast

### ISSUE THREAD

**Issue by alexisvincent** [clj-commons/aleph#276]
:) This would be really cool.

**Comment by ztellman** [comment]
You should be able to hack it in yourself via `pipeline-transform` and the code provided here: https://gist.github.com/mfilippov/10009192.  I'l look into how to expose it a bit more idiomatically.

**Comment by alexisvincent** [comment]
Awesome. Yeah I ended up doing that. But would be awesome to have it included. Shouldn't be too hard.

**Comment by alexisvincent** [comment]
Manifold/aleph are so cool btw. I'm new to Clojure, and these libs have really helped onboard me. 
Was significantly nicer to write a VOIP system using clojure and manifold, then what I would have done in Java :)

**Comment by maxcountryman** [comment]
@alexisvincent were you able to get this working? It seems like UDP sockets don't have a `pipeline-transform`.

**Comment by ztellman** [comment]
I should have said `bootstrap-transform`, which is provided.

**Comment by arnaudgeiser** [comment]
Let me close this issue, not because we don't want to offer this feature, but because we would like to know the expectations in terms of API.

Do not hesitate to reopen a new issue with your expectations.
