### ISSUE TITLE
namespace 'aleph.netty' not found

### ISSUE THREAD

**Issue by af-dan** [clj-commons/aleph#324]
Hi,
I'm trying to implement the udp namespace, but I'm keep getting a compiler exception `java.lang.Exception: namespace 'aleph.netty' not found, compiling:(aleph/udp.clj:1:1).`

I can clearly see it in the jar, and tried multiple versions of the library.
Any ideas?

**Comment by ztellman** [comment]
Usually that's because the namespace failed to load, which might be because
you have another version of Netty in your dependencies. Can you share the
output of 'lein deps :tree'?

**Comment by arnaudgeiser** [comment]
This issue is most likely a support request and not an issue per se.
I will close this one, do not hesitate to re-open if you need assistance.
