### ISSUE TITLE
Java 9/10 deps problem `javax.xml.bind.DatatypeConverter` missing

### ISSUE THREAD

**Issue by lyriccoder** [clj-commons/aleph#383]
When upgrading my JVM to 10.0.1 (or even 9.0.1) I get an error about the javax.xml.bind.DatatypeConverter class being missing. 

**Stack trace**
Caused by: 
java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter, compiling:(org/httpkit/client.clj:1:1) at clojure.lang.Compiler.load(Compiler.java:7526) 
at clojure.lang.RT.loadResourceScript(RT.java:379) 
at clojure.lang.RT.loadResourceScript(RT.java:370) 
at clojure.lang.RT.load(RT.java:460) 
at clojure.lang.RT.load(RT.java:426) 
at clojure.core$load$fn__6550.invoke(core.clj:6051) 
at clojure.core$load.invokeStatic(core.clj:6050) at clojure.core$load.doInvoke(core.clj:6034)

Adding :jvm-opts ["--add-modules" "java.xml.bind”] to my project.clj adds that class back, but if it's possible to update aleph to not depend on this module, that would be easier to use.

**Java version:**
java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)

**Comment by gsnewmark** [comment]
What version of Aleph are you using? I think this particular issue was fixed since 0.4.5-alpha1

**Comment by danielcompton** [comment]
It looks like this was fixed in https://github.com/ztellman/aleph/pull/337, since 0.4.5-alpha1 as @gsnewmark says. 

> This makes aleph client unusable on JVM 9/10 which I consider serious.
> I can use :jvm-opts ["--add-modules" "java.xml.bind”] option in project.clj, but I would like the bug to be fixed

I don't think this was your intent, but your comments here come across as demanding. Something like this could have been a better way to state your issue:

> When upgrading my JVM to 10.0.1 (or even 9.0.1) I get an error about the javax.xml.bind.DatatypeConverter class being missing. [Add stack trace here] Adding `:jvm-opts ["--add-modules" "java.xml.bind”]` to my project.clj adds that class back, but if it's possible to update aleph to not depend on this module, that would be easier to use.

**Comment by lyriccoder** [comment]
I am using 0.4.5-alpha6

**Comment by gsnewmark** [comment]
Based on your stacktrace it's problem in `http-kit`, not Aleph :thinking: 

```
Caused by:
java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter, compiling:(org/httpkit/client.clj:1:1) 
```

(source here is `org/httpkit/client.clj`)

Do you have both these libs on your classpath?

**Comment by lyriccoder** [comment]
Sorry for this thread.  httpkit was in project.clj
You can close the ticket

**Comment by tirkarthi** [comment]
@lyriccoder http-kit 2.3.0 resolves the JDK 9 issue.
