### ISSUE TITLE
Compile a list of Aleph users

### ISSUE THREAD

**Issue by ztellman** [clj-commons/aleph#450]
We'd like to get a list of companies/organizations using Aleph in production (and which pieces of Aleph they're using), both for bragging rights and to understand who the stakeholders are in future design discussions.  If you're using Aleph, please respond to this issue with any details you can provide.

**Comment by mccraigmccraig** [comment]
we ([yapster](https://yapster.info)) are using aleph via [juxt/yada](https://github.com/juxt/yada)

we have an http rest/json api, and also use websockets quite a lot. we do multipart upload with the implementation that yada provides. we're heavy users of manifold deferreds and streams

**Comment by gsnewmark** [comment]
We're using following pieces of Aleph at [Attendify](https://attendify.com/):

- HTTP client: mostly internal inter-service communication, as well as using REST APIs of internal data storages
- HTTP server: both internal services and public-facing APIs (a variant of JSON-RPC in both cases)
- Multipart support

We've also tried proxy support in HTTP client & WebSockets support, but not currently using it in production.

Not directly connected to Aleph, but quite a lot of our code also uses Manifold's deferred to define async operations.  We're not using streams that much though.

**Comment by piranha** [comment]
[Kasta](https://kasta.ua) uses Aleph for the following:

- HTTP server: our web servers use Aleph.
- HTTP client: we have some (not much) internal communication through HTTP APIs, where we use Aleph as client (together with multipart support).
- Websockets: public service, where we provide current information on product stocks. Every client (be it web or app) opens a connection to websockets, so they sustain some load.

**Comment by jhimanka** [comment]
[Priima LMS](https://priimalms.com/) uses Aleph as a ring-compatible HTTP server. Pretty basic functionality now but we are looking into asynchronous cases and Manifold.

**Comment by retief** [comment]
organizetogether.com is using the aleph web server as our main web sever, and all of our server code is built around manifolds.  We're also using the aleph http client to talk to external services whenever reasonable (mostly because it uses manifolds).  We're using sente and sente's aleph adaptor for websockets.

In practice, our server code is built around manifolds, then we convert the resulting manifold-based handler to a cps style so we can use ring middleware, and then we convert the cps style handler back into a manifold based one in order to pass it to aleph.  It works, but the result feels a tad clunky.

**Comment by jcf** [comment]
A number of companies and clients I’ve worked with use the Aleph HTTP client and Manifold in production, and a small number of clients used Yada (which as already mentioned is built on top of Aleph).

Aleph and Manifold will play a role in some of my upcoming work, and I’m happy to discuss some of the details privately if that would be helpful.

**Comment by ztellman** [comment]
@jcf feel free to contact me with any details you're not comfortable sharing publicly

**Comment by scramjet** [comment]
[Systematic](https://systematic-app.com) is using Aleph in production for both client websocket connections, and for serving web pages at signup (+ Ring + Hiccup + Garden).

We're making active use of Aleph's async request/response support in Ring, and Manifold's integration with core.async (most of our async logic is in core.async, although we'll likely experiment with using Manifold directly at some point).

In future, we'll likely also use Aleph for providing a B2B REST API for our clients.

We love Aleph for many reasons, but it's especially nice for us because we already have a heavy investment in Netty for our other backend services (APNs, DNS, etc).

**Comment by danjohansson** [comment]
KPSystem in Sweden is using the following Aleph functionality: webserver, client, websockets and multipart.
We are very happy with it!

**Comment by alexander-yakushev** [comment]
[Grammarly](https://grammarly.com) uses Aleph in a part of its backend stack. Things used substantially: HTTP server, HTTP client, asynchronous flows with Manifold, fine-tuned and monitored executors and pools.

**Comment by pyr** [comment]
Hi!

After a detour through some direct Netty interaction - mostly as a learning exercice - [Exoscale](https://exoscale.com) now defaults to aleph and manifold for the following in Clojure:

- RPC servers and clients
- HTTP servers and clients
- Most database clients

Thanks a lot for your work!

**Comment by rborer** [comment]
[Finity.ai](https://finity.ai/) is using Aleph for our internal counters & events component. Aleph HTTP server is used there, responding to roughly 7.5 million requests per day.

We also have started work to transition our web crawler (crawling ~ 26 million URLs per day) from our venerable internal Netty 3.10 wrapper into Aleph. It's a long process as I realized that our current execution model had a few quirks. It's currently running on our testing infrastructure and I intend to deploy it to production beginning next year (I still have to figure out why it gives an OOM every few days of runtime...).

We're also relying a lot on manifold for our whole stream processing platform (which is really awesome btw!).

**Comment by superstructor** [comment]
@flybot-sg (Flybot Ltd, Singapore) is using it for our HTTP+WebSocket APIs for all sorts of multiplayer game services. Clients are built with the Unity game engine.

**Comment by fmnoise** [comment]
Eventum.no is using Aleph for HTTP(servers and clients) and SSE. We also use Manifold for async flows.

**Comment by lvh** [comment]
We (Latacora) use Aleph/Manifold for some software that talks to AWS a bunch. (It's not a particularly judicious use of Aleph, since it's all blocking AWS SDK goop under the hood.)

**Comment by jeroenvandijk** [comment]
At [adgoji](https://www.adgoji.com), we're using the Aleph http server as the main http endpoint of our [realtime bidder](https://en.wikipedia.org/wiki/Real-time_bidding), running on 50-100 servers.

We use [Engulf](https://github.com/andrewvc/engulf), an application that is build upon (an older version of) Aleph, for load testing. We are using [yada](https://github.com/juxt/yada) in several of our internal endpoints. We use manifold in a lot of our async code as it is more composable than core.async.

**Comment by miikka** [comment]
At Metosin, I'm using Aleph in one project as a HTTP server and I written some HTTP API clients with it as well.

**Comment by dev-smx** [comment]
[Smxemail](http://smxemail.com) uses Aleph for our internal HTTP APIs to the components of our email archive and analytics products running on Azure.

**Comment by csm** [comment]
At [Noon Home](https://www.noonhome.com) we use Aleph in a number of publicly-facing and internal HTTP services; we also use the HTTP client for communication between services. We use the TCP server, with TLS, for all communication with our devices in the field, and use TCP client and server for an internal message queue we developed in-house.

**Comment by aengelberg** [comment]
At [Amperity](amperity.com) we:
* use the Aleph HTTP server for our externally-facing microservices, wrapped with [Yada](https://github.com/juxt/yada) to give us routing and some more HTTP features for free.
  * largely dealing with small payloads, but we have a couple of file-upload endpoints that exercise Aleph's streaming capabilities and parse multi-part form data.
* batch-load data to/from various external APIs with the Aleph HTTP client.
* use Manifold deferreds and async composition religiously around the codebase, even for our internal microservices which are backed by [finagle-clojure](https://github.com/finagle/finagle-clojure), not Aleph.

**Comment by bostonaholic** [comment]
At CircleCI, we use it in a few different services. As of yet, we are utilizing only `aleph.http/start-server` for some internal and externally exposed services. Routing handled by ring and compojure.

**Comment by tanzoniteblack** [comment]
At [Yummly](https://github.com/yummly), we use aleph (via [yada](https://github.com/juxt/yada)) for the API responses that drive our smart oven & app integration ([Whirlpool new release on this](https://www.whirlpoolcorp.com/yummly-2-0-will-integrate-curated-cooking-experiences-into-whirlpool-kitchen-appliances/)), but currently don't actively use it to make http requests or to serve the traffic that runs our [website](https://www.yummly.com/) (we use http-kit for that).

We are, however, starting to become very heavy users of manifold in our main API.

**Comment by mrijk** [comment]
[VakantieDiscounter](https://www.vakantiediscounter.nl/) uses Aleph (as http client) mostly for async calls to our internal API's, as well as asynchronous flows with Manifold.

**Comment by bhurlow** [comment]
We use Aleph at [yellowdig](https://yellowdig.com/) for general HTTP server needs, as well as streaming for large data sets

**Comment by JarredLHumphrey** [comment]
We use Aleph at [Adaptly](http://adaptly.com/) (recently acquired by Accenture) as an http client for high volume requests to 3rd party apis.

**Comment by ztellman** [comment]
I've just been told there's the possibility of [Clojurists Together](https://www.clojuriststogether.org/) sponsoring work on Aleph.  If anyone has pain points they'd like to see addressed in Aleph, or is interested in having their own work on Aleph being sponsored, please contact me.

**Comment by vigneshsarma** [comment]
We the Identity team at [SAP Concur](https://www.concur.com/) uses Clojure and aleph in many of the services we run. We use both the HTTP client and server.

**Comment by cddr** [comment]
It has recently been introduced in the testing component of Funding Circle's kafka library (https://github.com/FundingCircle/jackdaw). We use async http requests to exercise tests against the confluent rest proxy, and just ported the internals of the test-machine which uses manifold to improve e2e test resiliency.

**Comment by johanatan** [comment]
I’m using Aleph’s ‘http client’ and Manifold’s ‘deferred’ for my personal software projects.

**Comment by ryuuseijin** [comment]
Atlassian Confluence's collaborative editing service Synchrony is using aleph and manifold together with core.async. Aleph is used for websocket support, to talk with browser clients as well as for communication within cluster nodes.

Aleph streams are hooked up on the edges to core.async channels and most of the logic has been implemented in core.async. In restrospect I think it would have been better to embrace aleph streams more fully as they are a richer abstraction and better to work with than core.async channels.

Aleph has been working very well at a relatively high scale (10s of thousands of messages per second).

**Comment by lispyclouds** [comment]
[Zalando](https://github.com/zalando)'s in-house Continuous Delivery Platform is using Aleph as the server to implement the CI/CD service.

It serves as the main entry point into the entire service, serves out the GraphQL API and maintains long connections to various services and performs well with less resources consumption.

**Comment by taurauko** [comment]
[Teachme Biz](https://biz.teachme.jp) uses Aleph for its Salesforce connector service.

**Comment by jeaye** [comment]
We at [OkLetsPlay](https://okletsplay.com) use this for our in-house Firebase alternative.

**Comment by ztellman** [comment]
I've opened an issue with @clj-commons to discuss the possibility of formally handing off stewardship of this project: https://github.com/clj-commons/meta/issues/59.  If anyone in this thread would like to potentially become a maintainer, please say so in that thread.  I would be happy to spend whatever time is necessary to get the maintainer (or, ideally, maintainers) up to speed on the internals of the library.
