### ISSUE TITLE
Test cases to cover HTTP requests pipelining on the server

### ISSUE THREAD

**Issue by kachayev** [clj-commons/aleph#456]
HTTP pipelining support is [not obvious](https://github.com/ztellman/aleph/blob/be1ee04c130660ce69ee7c6603132b36be79ec1f/src/aleph/http/server.clj#L179) and is not covered with tests.

**Comment by arnaudgeiser** [comment]
I agree with the statement but it's not pretty obvious how to write unit tests that demonstrate the behaviour of the pipelining.
I would rather propose to rely on integration tests to ensure it's working correctly, we are deeply inside the internals here. 

Closing this issue, do not hesitate to reopen if you disagree.
