### ISSUE TITLE
JVM 11 issue w/ clj-tuple on byte-streams$convert

### ISSUE THREAD

**Issue by hkupty** [clj-commons/aleph#520]
Hi,

Sorry for all the assumptions I have for this issue, but the I'm getting the following exception:
`class clojure.lang.PersistentUnrolledVector$Card1 tried to access field clojure.lang.APersistentVector._hash`.

It happens whenever I get a response when using `aleph.http/request`.

As far as I understood the stacktrace and tracked down through the projects' source code, `byte-streams` uses `clj-tuple` under the hood, which is archived and unmaintained for 4 years at least. I assume the class it's using (`PersistentUnrolledVector`, from `clj-tuple`) is incompatible w/ JVM 11, as the same code works under JVM 1.8.

I've pasted the stacktrace [here](https://pastebin.com/kBdbntTr).

If you need any extra information, please let me know.

Thanks in advance,
Henry Kupty

**Comment by hkupty** [comment]
Just an update:

The issue happens when I dynamically load the client. I've added the dependency statically now and it works normally.

I can consider this fixed for now, though I'd still prefer it to be dynamically loaded.

If you want to close the issue as w/ `won't fix` it's fine.

**Comment by igrishaev** [comment]
I'm facing the same issue when using Aleph as a part of my custom Kafka Connect plugin (Kafka Connect loads jars dynamically).

**Comment by KingMob** [comment]
@igrishaev @hkupty Try 0.4.7-alpha10, and let me know if it has the same issue
