### ISSUE TITLE
Some of the MDC is lost when aleph logs 

### ISSUE THREAD

**Issue by vigneshsarma** [clj-commons/aleph#529]
Due to the threading involved and logs like https://github.com/ztellman/aleph/blob/master/src/aleph/http/client.clj#L121 lose the mdc context. 

Any ideas on how we might solve this?
I was considering creating a custom thread pool and copy the context over by overriding submit. 
Another option might be to allow the caller to get a callback on these kinds of errors.

**Comment by KingMob** [comment]
@vigneshsarma 

Logging that swallows exceptions is a bit of a separate issue, which is mentioned elsewhere, iirc, but in general, MDC has to be ferried over when using thread pools.

Generally, you want to snapshot the MDC (MDC/getCopyOfContextMap) at the time of handler fn creation, and set it at the start of your handler fn (MDC/setContextMap). Overriding submit with a decorator thread pool would work. Personally, I've written `with-mdc` macros that handle the pattern transparently over the years.

Closing for now, unless you think there's more.
