### ISSUE TITLE
Unable to pass SSL context when creating a websocket client

### ISSUE THREAD

**Issue by FastLabs** [clj-commons/aleph#530]
SSL context when creating a websocket client

**Comment by kachayev** [comment]
`http/websocket-client` supports `ssl-context` option, [here](https://github.com/aleph-io/aleph/blob/01fe8695ab78892266cb3aebcb4645a7b2c360f8/src/aleph/http.clj#L210). Doesn't it work as excepted? 🤔

**Comment by KingMob** [comment]
Closing for age and lack of confirmation. If this is still a problem, @FastLabs , please let us know.
