### ISSUE TITLE
Update the netty version

### ISSUE THREAD

**Issue by nagatoism** [clj-commons/aleph#531]
Currently the netty version used in aleph is 4.1.36.Final which is last update 30 Apr 2019.
The newest version for netty is already 4.1.43.Final and there are a few bugs fixed.
Can we have an update of netty version to the newest?

**Comment by rborer** [comment]
I already opened #525 a while ago to bump to 4.1.42 which is still not merged..

**Comment by KingMob** [comment]
Latest alpha is on 4.1.64.Final. I'm waiting on deployment creds, but in the mean time, you can test by downloading and installing locally.
