### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by ertugrulcetin** [clj-commons/aleph#539]
Is this project still under active development or has it been effectively abandoned? I see PRs not getting merged and issues don't have responses which is a bit sad.

**Comment by rborer** [comment]
I've been wondering too due to the absence of recent activity. Maybe a good candidate for https://clj-commons.org/ ?

**Comment by rymndhng** [comment]
I'm also wondering the same. `aleph` has been fantastic at our high throughput needs. 

There are a few maintenance items that would be nice to address, for example upgrading `netty` deps that have security vulnerabilities.

**Comment by ztellman** [comment]
Hi, I'm sorry I haven't given this project much attention over the last few years.  Since I no longer work at a company where this is a foundational piece of tech, I can't do maintenance during my typical work day, and more generally it's not on my mind nearly as often.

The original plan was to hand things off to @kachayev, but he also started working at a new job where Aleph isn't in use.  If someone else would like to volunteer to maintain the project, I'd be happy to speak to them.  Otherwise, I'll try to at least remain up-to-date on Netty releases, and think about what would be required to reach a "stable" 1.0 release that addresses all known issues.

**Comment by ertugrulcetin** [comment]
@ztellman thank you for the update, I totally understand.

**Comment by rborer** [comment]
Thanks for the update @ztellman . I definitely understand your situation.

I would love to help in maintaining Aleph as this is clearly an important element of clojure ecosystem. But I do not feel knowledgeable enough to carry this burden alone. I've only surfaced Netty, so while I can help review clojure code I'm still having a hard time figuring out how everything works.

If I understand your idea within #441 was to find a single person to take the lead on the project. I am wondering if, given the current situation, a group of people would be a better fit. What do you think?

**Comment by kachayev** [comment]
As Zach have already mentioned, I changed my job last year. Even though I had been enjoying contributing to the project for quite some time, nowadays I don't use Aleph (I barely work with any networking tech at all). More significantly, I don't use Clojure at work and, unfortunately, I don't have enough time to stay in touch with the community (or at least to track recent changes and events). I would be more than happy to help push some of my recent PRs to a finish line, those with bug fixes or comparably small improvements. Large PRs with significantly new functionality should be probably "frozen" as of now to avoid introducing new issues or unstable behavior. 

@ztellman do you have a specific plan (or ideas) about 1.0 version (what should be merge or what is missing)? I can review my own unmerged PRs and point out those that are good candidates to be included into the next stable release.

**Comment by rymndhng** [comment]
Thank you both @ztellman, @kachayev for the countless hours to make aleph where it is today. I have the same sentiments as the other folks here: maintainers have no obligation to anyone. 

I also have the same sentiment as @rborer. I'd love to help out but I've only started scratching the surface of `netty`.

**Comment by vlifeng** [comment]
Thank you @ztellman & @kachayev

**Comment by dspiteself** [comment]
My company relies on Aleph. I would be be interested in participating.

**Comment by ztellman** [comment]
> @ztellman do you have a specific plan (or ideas) about 1.0 version (what should be merge or what is missing)? I can review my own unmerged PRs and point out those that are good candidates to be included into the next stable release.

I would need to get back do a review to get back up to speed on all of this.  If you want to add a `1.0` label to any PRs that you think are obvious candidates to include, that would be very helpful.

**Comment by kachayev** [comment]
@ztellman Sure, will do!

**Comment by maleghast** [comment]
Just wanted to add my voice to the list of people who would be very interested in helping out, with the huge caveat that I would need to do some serious learning about Netty and all of that, but I would definitely be prepared to do that as where I work we do all our system / infrastructure programming in Clojure, and that means APIs and Aleph has served me very well in the past on that front...  I am pretty sure that I could make a case for contributions to this to be a part of my working life, as long as I was not trying to carry it on my own.

**Comment by solatis** [comment]
Is it perhaps an idea to talk with the people of clj-commons to see if that’s an option? I’m fairly certain both aleph and manifold would qualify, and it would provide a more community driven maintenance model for these projects. In my opinion these libraries are one of a kind, and heavily depended upon in many projects. 

If there’s anything I can do to help, let me know.

**Comment by ztellman** [comment]
That sounds like a decent idea, I'll reach out to the clj-commons folk and see what they think.

**Comment by ztellman** [comment]
I've opened an issue with @clj-commons, anyone who thinks they might be interested in contributing to the future of the project should speak up there: https://github.com/clj-commons/meta/issues/59.
