### ISSUE TITLE
get to v1.0

### ISSUE THREAD

**Issue by ztellman** [clj-commons/aleph#555]
The immediate goal, post hand-off to clj-commons, is to get people feeling comfortable making contributions, work through the issue backlogs, and cut v1.0 releases for all the libraries, representing a stable version of the current feature sets.

Here's my rough sense for how we can get there:
* I will go through all the projects and make sure there are decent namespace-level comments in every file (there should already be high-quality function doc-strings throughout, though if I've missed anything people should point it out).
* All issues should be tagged with their level of difficulty (easy, moderate, hard), where "easy" issues are suitable for new contributors, "moderate" for people with a passing familiarity, and "hard" may need to be reserved for existing experts.
* People assign themselves issues as they see fit, and ask for help whenever they need it.
* If parts of the codebase are unexpectedly confusing, people can open a documentation bug and assign it to me.

If we have too many non-easy issues, we can try a hybrid approach where a more experienced contributor outlines a likely solution, and a less experienced contributor tries to put it into effect. 

All PRs should be reviewed by either @kachayev or myself before merging.  If someone else feels comfortable playing the role of reviewer, let me know, I'd be happy to have the help.

This can serve as a place for tracking overall progress on our work, and any meta-discussion of how we want to approach it.

cc @kachayev @KingMob @valerauko @tanzoniteblack @frap @abhishekamralkar @solatis @greglook @slipset @danielcompton @borkdude @lread

**Comment by kachayev** [comment]
Hey @ztellman, thanks for putting it all together! There's one PR I would like you to review/comment on: [errors handling](https://github.com/clj-commons/aleph/pull/553). This is the last change I considered before wrapping 1.0 (not counting issues/fixes). After this PR is merged into 1.0 branch, I assume, we can release an artifact to let users to test it out.

I can check all existing issues to identify difficulty level. But what's more interesting and challenging question: how will we proceed with new feature requests or suggestions? Typically, such tickets require deeper understanding of the project compared to implementation-only concerns. WDYT?

**Comment by valerauko** [comment]
I think I've got a pretty good understanding of how it works, so I can help with documenting the netty and http namespaces if needed.

**Comment by KingMob** [comment]
Hi @ztellman / @kachayev , I thought I'd take the initial step of labeling the existing issues in byte-streams as easy/moderate/hard to get the ball rolling, but I don't have the permissions to do so in GH. Who grants perms for that (assuming it's not something you two want to reserve for yourselves)?

**Comment by slipset** [comment]
@KingMob I've invited you as a maintainer to this repo, so you should be able to (amongst other things) triage issues

**Comment by KingMob** [comment]
> @KingMob I've invited you as a maintainer to this repo, so you should be able to (amongst other things) triage issues

Thanks @slipset! What about other repos like byte-streams and manifold? I'm currently crafting a PR for an old issue on byte-streams.

**Comment by slipset** [comment]
Sorry about that @KingMob, I was being a computer. You're now maintainer of all the other aleph related libs as well.

**Comment by frap** [comment]
Hi, I have time freed up now that i can help on this? I see it hasnt moved much since jan. What can I do to help move these to a 1.0.0 release?

**Comment by KingMob** [comment]
@frap Still want to help? We have lots of outstanding issues, and PRs that need reviewing. arnaudgeiser is working to bring Oleksii's 1.0.0 branch into master bit-by-bit, if you want to reach out to him.

**Comment by frap** [comment]
Sure , Ill take a look

regards Gas
---
Gas ***@***.***
Home: WWWF+6MW
+64 21 629488
“The world wants to know if you have cojones?"  -- Emilio Perez *All the
Pretty Horses*
<https://click.convertkit-mail4.com/zluzgmm5kvunhlk0lzup/25h2hoh73vq9gxi3/aHR0cHM6Ly9nZW5pLnVzL1k3VEVjOUE=>

**Comment by arnaudgeiser** [comment]
Finally! I guess we can close this PR.
Not all commits from the `1.0.0` branch have been integrated, nor the commits from the `error-handling` branch, but most of the relevant ones (or at least the ones we were comfortable with).

A __1.0__ version is not on the agenda anymore, which is a good news.
