### ISSUE TITLE
ZeroMQ channel

### ISSUE THREAD

**Issue by auser** [clj-commons/aleph#58]
Hey Zachary,

I'd love to see ZeroMQ supported as a transport mechanism. I have checked out the source and will definitely see if I can implement something... 

Any thoughts on where I should start? I'm thinking in aleph.redis is a good place to look into...

**Comment by benjyz** [comment]
@ztellman given that there is now a pure Java version (JeroMQ) any thoughts on coupling aleph and Jeromq?

**Comment by ztellman** [comment]
Aleph is basically Netty + Manifold.  I think a JeroMQ + Manifold library is a great idea, but I'm pretty sure that should be a second library.
