### ISSUE TITLE
0.4.7-rc1 compiled with java17

### ISSUE THREAD

**Issue by xificurC** [clj-commons/aleph#580]
The latest jar seems to be deployed with java17 compiled java class files. Is this intended?

**Comment by KingMob** [comment]
@xificurC Whoops. No, it wasn't. I'll cut an rc2 compiled for Java 8.

**Comment by danielcompton** [comment]
You can set the java options like this so that you can compile with newer JDKs but still include support for older ones:

https://github.com/clj-commons/primitive-math/blob/4d6f219860a66983913a034f878aec442473f33e/project.clj#L17

I think source and target set to 1.8 should work.

**Comment by KingMob** [comment]
Thanks @danielcompton. 

Erik and I were also discussing a more comprehensive deployment process based on http://slipset.github.io/posts/deploying-to-clojars. We'd already done it for byte-streams, but it would be good to extend that to aleph and manifold, too. Manual deployment is obviously error-prone 😄
