### ISSUE TITLE
:follow-redirects? does not follow through

### ISSUE THREAD

**Issue by jetmind** [clj-commons/aleph#597]
```
› cat deps.edn 
{:deps {aleph/aleph {:mvn/version "0.4.7"}}}

› clj
Clojure 1.10.3
user=> (require '[aleph.http :as http])
nil
user=> (-> (http/request {:method :get :url "http://httpbin.org/status/301" :follow-redirects? true}) deref :status)
301
```

expected status 200

**Comment by akovantsev** [comment]
code has `(false? (opt req :follow-redirects))`, without`?`
https://github.com/clj-commons/aleph/blob/a0c64061bdca88f0e227a52bd3aeb98dd4257faa/src/aleph/http/client_middleware.clj#L309

docs have `:follow-redirects?`, with `?`
https://github.com/clj-commons/aleph/blob/8850c3bc78a6df782fd983fbec1eb8b7f16e5a57/src/aleph/http.clj#L287
https://github.com/clj-commons/aleph/blob/6a88b4d3daa4329ce10642fd86a57b3c034c7599/CHANGES.md#L160

**Comment by jetmind** [comment]
Ok, I shoud have used `:request-method` instead of `:method`. Everything works.

**Comment by KingMob** [comment]
Hmmm, not so fast. There's the `aleph.http.client-middleware/wrap-method` in the default middleware that should fix this exact issue.

**Comment by KingMob** [comment]
There's also a discrepancy in the keywords/docs between `follow-redirects?` and `follow-redirects`

**Comment by KingMob** [comment]
The issue is that the chained fn that handles the response, reuses the _original_ request map for some things, namely cookies and the request method, from before the request middleware was applied. After a close reading, I don't think the cookie code is impacted, but this explains why `wrap-method` didn't fix it.
