### ISSUE TITLE
TCP server invokes handler when connection closes prematurely during TLS handshake

### ISSUE THREAD

**Issue by DerGuteMoritz** [clj-commons/aleph#618]
Using `b41471529f023ef82595353dc2e9f3db548e3abf`, when the client prematurely closes the connection during the TLS handshake, the server's handler gets invoked with a placeholder session object just like it was before https://github.com/clj-commons/aleph/pull/608 went in. 

Reproducer:

```clojure
(aleph.tcp/start-server
 (fn [_ c] 
   (prn :hello (:ssl-session c)))
 {:port 12345
  :ssl-context (aleph.netty/self-signed-ssl-context)})

(s/close! @(aleph.tcp/client {:host "localhost" :port 12345}))
```

Server output:

```
:hello #object[sun.security.ssl.SSLSessionImpl 0xbfa7bfa "Session(1660918752778|SSL_NULL_WITH_NULL_NULL)"]
```

I've been able to trace this down to `aleph.netty/operation-complete` (as used by `aleph.netty/wrap-future`): [Turns out that it resolves the deferred as successful (albeit with a `false` value) in case the future failed with a `ClosedChannelException`](https://github.com/clj-commons/aleph/blob/master/src/aleph/netty.clj#L234-L237). This behavior was introduced with https://github.com/clj-commons/aleph/commit/1805783bfc05851c0c49a7da34bf481cdb41b925 but it doesn't explicitly state why. @KingMob @arnaudgeiser What's your take on this? Seems a bit fishy ...

In any case, I'll prepare a patch for making the future success handler look at the value and only invoke the handler when it's truthy so that we have a symptomatic fix for the time being.

**Comment by arnaudgeiser** [comment]
> This behavior was introduced with https://github.com/clj-commons/aleph/commit/1805783bfc05851c0c49a7da34bf481cdb41b925 but it doesn't explicitly state why. @KingMob @arnaudgeiser What's your take on this? Seems a bit fishy ...

I don't have a __good__ answer to this.
The only thing I can tell is that's a pattern we are also using a lot on our codebase.
If the client cuts the connection, let's consider it was successful from a server point of view.

Sorry for the non-answer...

**Comment by KingMob** [comment]
@DerGuteMoritz My first guess was it's for compatibility with manifold streams. `put!` and `take!` always return success-deferreds, with either true if the operation succeeded, or false if they failed.

But after a bit of thinking, I'm not so sure. I suspect it's related to ClosedChannelException being a "soft" error. I.e., according to the docs, you could close a channel for reading, but not writing, in which case read ops will get the ex, but write ops should still succeed, no problem. 

Unfortunately, this breaks the `put` of ChannelSink, IIUC. As seen in https://github.com/clj-commons/aleph/blob/93e6c7b0122f92fd10b68e9555a85feac952ddba/src/aleph/netty.clj#L420-L424, if `write-and-flush` fails because the channel was closed, it will still report true, which it shouldn't. I tried to do an audit of the other uses of wrap-future, and either they don't care about the return value, or they're wrapping close/terminationFutures already, in which case one would hope those futures aren't failing due to already being closed 😄 

I tried reverting the check for ClosedChannelException, and no tests fail. Moritz, if you try that, does it solve your issue?

**Comment by DerGuteMoritz** [comment]
@KingMob Thanks for checking the other `wrap-future` uses, this was still on my todo list, too :+1: The `ChannelSink` case you cite also seems like a bona fide bug to me. If you like I could try to construct a regression test around this.

I can confirm that removing the `ClosedChannelException` specal-case from `operation-complete` also makes the regression test I added in https://github.com/clj-commons/aleph/pull/619 pass. If you like, I'll adjust the PR accordingly!

**Comment by DerGuteMoritz** [comment]
OK just read your comment over at the PR to that effect - will adjust!

**Comment by DerGuteMoritz** [comment]
> The `ChannelSink` case you cite also seems like a bona fide bug to me. If you like I could try to construct a regression test around this.

Just gave this a shot and it seems to behave fine. I think this is because the `sink` constructor function also wraps it in a `closeFuture` which intercepts the close event before it hits the completion handler:

https://github.com/clj-commons/aleph/blob/9f8667dd5ebb87987edc80615265e106d61fb747/src/aleph/netty.clj#L445-L447

The test passes both with and without the `ClosedChannelException` special-case handling, i.e. `put` returns false as expected after the backing channel closes. I was only able to make it fail when removing the `closeFuture`. I'll also add the test to the PR for good measure, we can then discuss further details over there.

**Comment by DerGuteMoritz** [comment]
I think I found another case which doesn't properly handle the `false` success:

https://github.com/clj-commons/aleph/blob/9f8667dd5ebb87987edc80615265e106d61fb747/src/aleph/http/server.clj#L844-L852

Though it seems a bit more benign than the `SslHandler#handshakeFuture` case.

**Comment by KingMob** [comment]
> > The `ChannelSink` case you cite also seems like a bona fide bug to me. If you like I could try to construct a regression test around this.
> 
> Just gave this a shot and it seems to behave fine. I think this is because the `sink` constructor function also wraps it in a `closeFuture` which intercepts the close event before it hits the completion handler:
> 
> https://github.com/clj-commons/aleph/blob/9f8667dd5ebb87987edc80615265e106d61fb747/src/aleph/netty.clj#L445-L447
> 
> The test passes both with and without the `ClosedChannelException` special-case handling, i.e. `s/put!` returns false as expected after the backing channel closes. I was only able to make it fail when removing the `closeFuture`. I'll also add the test to the PR for good measure, we can then discuss further details over there.

I'm not sure how this is related to attempting to `put` after a ChannelSink is closed. Also, I'm not sure what you mean by "intercept". All listeners of a future are triggered when done. They can't intercept the event and prevent others from triggering (not reliably, anyway).

`put` in ChannelSink checks for `closed?` at the top, but there's nothing preventing it from passing the check, having its thread paused, while another thread closes the channel before the `put` thread resumes. It will be rare, but I'll bet it happens occasionally. I can see how removing the `.closeFuture` code you linked to makes it happen much more frequently, but I don't think that code's presence prevents the errors entirely.

With multithreading, absence of evidence is never evidence of absence 😄 I'll bet if you try to race a putter and a closer 100000 times, you'll turn up some errors.

**Comment by KingMob** [comment]
> I think I found another case which doesn't properly handle the `false` success:
> 
> https://github.com/clj-commons/aleph/blob/9f8667dd5ebb87987edc80615265e106d61fb747/src/aleph/http/server.clj#L844-L852
> 
> Though it seems a bit more benign than the `SslHandler#handshakeFuture` case.

Good catch. I didn't audit this thoroughly enough. This seems like one of the locations that doesn't care about the result at all, only that it's done, but if the channel was closed before the handshake completes, the future will fail with a ClosedChannelException, yet it will still try to proceed with the websocket stream when it shouldn't.

**Comment by KingMob** [comment]
@DerGuteMoritz LMK when it's time to take another look

**Comment by DerGuteMoritz** [comment]
@KingMob 

>  Also, I'm not sure what you mean by "intercept". All listeners of a future are triggered when done. They can't intercept the event and prevent others from triggering (not reliably, anyway).

I assumed that because the `.closeFuture` is registered last, it might get invoked first and close the stream before a pending `write-and-flush` future would get a chance to produce a bogus result. However, I hadn't read the code around this closely enough. This hypothesis doesn't make sense after all, so never mind :-)


> `put` in ChannelSink checks for `closed?` at the top, but there's nothing preventing it from passing the check, having its thread paused, while another thread closes the channel before the `put` thread resumes. It will be rare, but I'll bet it happens occasionally. I can see how removing the `.closeFuture` code you linked to makes it happen much more frequently, but I don't think that code's presence prevents the errors entirely.

Thanks, that fills in the blank in my undersanding, had completely missed that TOCTTOU race there. But unless I'm mistaken, our change to `operation-complete` should mitigate this. I just don't see a good way to produce a (reliable enough) regression test for this :thinking: 


> With multithreading, absence of evidence is never evidence of absence smile I'll bet if you try to race a putter and a closer 100000 times, you'll turn up some errors.

Right, I erroneously assumed that the error you described was fully deterministic in nature (i.e. the situation I built the test case for). Thanks for clarifying :+1: 

> LMK when it's time to take another look

I'd say the PR is good to go as-is unless you actually *do* want me to come up with a regression test for the race condition :smile:

**Comment by KingMob** [comment]
The fix for the TOCTTOU is also to stop treating ClosedChannelException specially, so I think were good there.

I don't think we need to craft a special race regression test, but I was reading Hillel's [post on metamorphic testing](https://www.hillelwayne.com/post/metamorphic-testing/), and wondering how we could craft more general tests (either metamorphic or standard generative/property-based) to better cover the system.

One interesting metamorphic test I just thought of: since Aleph aims for parity with clj-http in the client (aside from streams), we could run tests that feed in random input to both clj-http and Aleph's client, and verify that they return the same output, regardless of what the output actually is.

Anyway...

**Comment by DerGuteMoritz** [comment]
> The fix for the TOCTTOU is also to stop treating ClosedChannelException specially, so I think were good there.

Right, thanks for confirming :+1: 


> I don't think we need to craft a special race regression test, but I was reading Hillel's [post on metamorphic testing](https://www.hillelwayne.com/post/metamorphic-testing/), and wondering how we could craft more general tests (either metamorphic or standard generative/property-based) to better cover the system.

Cool, thanks for sharing that post! That would also combine pretty nicely with the (hopefully soon more reliable) resource leak detector. I'm getting some fuzz testing vibes, too :sunglasses: 


> One interesting metamorphic test I just thought of: since Aleph aims for parity with clj-http in the client (aside from streams), we could run tests that feed in random input to both clj-http and Aleph's client, and verify that they return the same output, regardless of what the output actually is.

Nice idea, sounds promising! Same could be done with the server component, comparing to e.g. `ring-jetty-adapter`.

**Comment by KingMob** [comment]
Good idea on the ring-jetty-adapter.

Yeah, it has fuzzing vibes, and property/generative vibes, for sure. Unlike fuzzing, metamorphic testing isn't looking for breakage. And unlike generative/property-based testing, we're not testing a known property of the output (like `double(x) % 2 == 0`). It's more about capturing output invariants that hold under transformation of inputs, but we don't care about the output _per se_.

So what would those look like for Aleph? Well, there's a lot of input formats (headers, multipart, compression, etc) that should all yield the same output body. Or, if we supported HTTP/2 or 3, we could test that response bodies remain the same regardless of protocol version. Aleph supports multiple byte-based formats that can be supplied to the output body, those could be tested, too.

In some cases, we already have tests like this, but they're _oracle_-based, in the sense that we compare against a known output. Anyway...food for thought. I think comparing the ring-jetty-adapter and clj-http would be pretty fruitful.
