### ISSUE TITLE
Wrong number of args (5) passed to: manifold.executor/thread-factory

### ISSUE THREAD

**Issue by falberto** [clj-commons/aleph#645]
Try create a new socket client ([aleph "0.6.0-rc1"])

```
(d/chain (tcp/client {:host host, :port port})
           #(wrap-duplex-stream protocol %))
```

`Execution error (ArityException) at aleph.netty/enumerating-thread-factory (netty.clj:1027).
Wrong number of args (5) passed to: manifold.executor/thread-factory`

![image](https://user-images.githubusercontent.com/1578072/202190937-1b8b2d18-56c6-449d-9331-ed879ec94687.png)

**Comment by arnaudgeiser** [comment]
Hello @falberto!

I seems you are explicitly defining a dependency on `manifold 0.2.3` while `manifold 0.2.4` is now required on Aleph with the latest versions.
Can I ask you to double-check?

**Comment by falberto** [comment]
you`re right.

Ty
