### ISSUE TITLE
Look into new Ring websocket support for Aleph

### ISSUE THREAD

**Issue by KingMob** [clj-commons/aleph#690]
### Summary

weavejester announced that the upcoming Ring 1.11 will have Ring syntax support for WebSockets. This issue is to look into support for it. See https://github.com/ring-clojure/ring/wiki/WebSockets

1. How easy will it be to retrofit Aleph to support it? 
2. How many users are interested in using the new listeners?
3. Are there any absolute blockers? 
4. What would be the benefits, if any? 

### Initial thoughts

Unfortunately, we haven't had a standard for websockets, so every server already has its own implementation. Thus, any interop value might take a while to materialize.

At a deeper level, Aleph is heavily stream-based, so the new event-based listener model is not a great fit. However, if people choose to use the new Ring listener model, it might be doable to slot the callbacks into Netty handlers, though the cost is skipping all of Manifold's streaming.

Finally, WebSockets are an older HTTP/1 technology. Once the HTTP/2 code is released and stabilized, I expect it to supplant Websockets over time. HTTP/2 streams in Aleph's raw-stream mode are effectively equivalent, with the added benefit of not requiring a whole TCP connection.

**Comment by vimalJD** [comment]
### Is this project is ongoing? Let me know further (DOCS) to contribute on it as "good first issue".

**Comment by KingMob** [comment]
@vimalJD DM me on the Clojurians Slack if you want to work on this.

**Comment by KingMob** [comment]
Replaced by #706
