### ISSUE TITLE
Question about single server process using both non-ssl and ssl

### ISSUE THREAD

**Issue by coreagile** [clj-commons/aleph#711]
Is there a way to run a single server that listens on both ssl and non-ssl ports? I couldn't figure it out. Here's how I did it with the ring-jetty9-adapter:

```clojure
(mount/defstate ^{:on-reload :noop} ^Server http-server
  :start
  (when (env :server-enabled?)
    (let [handler (w/app cfg-db)]
      (jetty/run-jetty
        handler
        (let [{:keys [keystore key-password-fn]} (ssl-options)]
          (merge {:join? false, :ssl? true, :h2? true, :async? false
                  :keystore keystore, :key-password (key-password-fn)}
                 (env))))))
  :stop (stop-server))

(defn stop-server []
  (when http-server (.stop http-server)))
```

And I ended up making it work this way with aleph, but I'd rather not have done it this way, as I'm assuming it uses up a bit more memory than I need to:
```clojure
(mount/defstate ^{:on-reload :noop} http-server
  :start
  (when (env :server-enabled?)
    (let [handler (w/app cfg-db)
          {:keys [port ssl-port]} (env)

          ^ApplicationProtocolConfig$SelectorFailureBehavior
          selector-failure-behavior
          ApplicationProtocolConfig$SelectorFailureBehavior/NO_ADVERTISE

          ^ApplicationProtocolConfig$SelectedListenerFailureBehavior
          listener-failure-behavior
          ApplicationProtocolConfig$SelectedListenerFailureBehavior/ACCEPT

          {:keys [key-manager-factory]} (keystore-fn)

          protocol-config
          (ApplicationProtocolConfig.
            ApplicationProtocolConfig$Protocol/ALPN
            selector-failure-behavior
            listener-failure-behavior
            [ApplicationProtocolNames/HTTP_2
             ApplicationProtocolNames/HTTP_1_1])
          ssl-context
          (-> (SslContextBuilder/forServer key-manager-factory)
              (.applicationProtocolConfig protocol-config)
              (.build))]
      {:http (http/start-server handler {:port port})

       :https
       (http/start-server
         handler
         {:port ssl-port
          :http-versions [:http2 :http1]
          :ssl-context ssl-context})}))

  :stop (stop-server))

(defn stop-server []
  (let [{:keys [http https]} http-server]
    (when (and http https)
      (.close http)
      (.close https))))
```

It's kind of weird because I have a background process that automatically renews the SSL cert using LetsEncrypt which unmounts and remounts the server at runtime after updating the certs.

Any advice welcome!

**Comment by KingMob** [comment]
There's no way to do that in Aleph, but you don't actually need to. The memory increase is miniscule. Under the hood, the "servers" will share the same Manifold thread pools, Netty classes/handlers/thread pools, JVM, etc. It's not like running a full-blown separate server process. As far as Aleph/Netty are concerned, it's the same server, but with a second socket listener that has a slightly different bootstrap procedure (add an SSL handler to the pipeline, support HTTP2 if ALPN negotiates it, etc).

FWIW, you should be able to stop and restart just the SSL server when you update the cert.

Sorry if that wasn't clear. Is there a place you would have expected to see that info in the docs?

**Comment by KingMob** [comment]
(BTW, the best place for questions like this is #aleph in the Clojurians Slack. You'll probably get an answer faster there.)

**Comment by coreagile** [comment]
Thanks for all the useful info!It’s funny that right in the README this kind of thing is hinted at but not explicitly called out. I’m not sure what would have helped. To do what I needed to do I had to read a lot of Netty documentation and the aleph source code. But perhaps that’s fine — my use case (starting up by automatically generating a self signed cert and then providing a UI to seemlessly switch to letsencrypt) seems to be unique. :-)Much appreciated!On Feb 13, 2024, at 02:35, Matthew Davidson ***@***.***> wrote:﻿
There's no way to do that in Aleph, but you don't actually need to. The memory increase is miniscule. Under the hood, the "servers" will share the same Manifold thread pools, Netty classes/handlers/thread pools, JVM, etc. It's not like running a full-blown separate server process. As far as Aleph/Netty are concerned, it's the same server, but with a second socket listener that has a slightly different bootstrap procedure (add an SSL handler to the pipeline, support HTTP2 if ALPN negotiates it, etc).
FWIW, you should be able to stop and restart just the SSL server when you update the cert.
Sorry if that wasn't clear. Is there a place you would have expected to see that info in the docs?
